apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-metric-generator
data:
  config.yml: |
    metrics:
      - name: gauge_demo
        help: gauge demo
        type: gauge
        label_keys: [k1, k2]
        sequences:
          - label_values: [v3, v4]
            interval: 10
            value: 10
            operation: inc
          - label_values: [v5, v6]
            interval: 10
            value: 1
            operation: dec
          - label_values: [v1, v2]
            interval: 10
            value: 10
            operation: set

